# connections.yaml

# Replace with your email
user_email: 'email@example.com'

# Platform-specific connection configurations
snowflake:
  user: '${SF_USER}'
  password: '${SF_PASSWORD}'
  account: '${SF_ACCOUNT}'
  database: '${SF_DATABASE}'
  schema: '${SF_SCHEMA}'
  warehouses:
    XS:
      name: 'WAREHOUSE_XS'
      price_per_hour: 1
    S:
      name: 'WAREHOUSE_S'
      price_per_hour: 2
    M:
      name: 'WAREHOUSE_M'
      price_per_hour: 3
    L:
      name: 'WAREHOUSE_L'
      price_per_hour: 4
    XL:
      name: 'WAREHOUSE_XL'
      price_per_hour: 5
    2XL:
      name: 'WAREHOUSE_2XL'
      price_per_hour: 6
    3XL:
      name: 'WAREHOUSE_3XL'
      price_per_hour: 7
    4XL:
      name: 'WAREHOUSE_4XL'
      price_per_hour: 8
    5XL:
      name: 'WAREHOUSE_5XL'
      price_per_hour: 9
  history_warehouse: 'WAREHOUSE_XS'

databricks:
  server_hostname: '${DBX_HOST}'
  access_token: '${DBX_TOKEN}'
  http_paths:
    2XS:
      path: '/sql/1.0/warehouses/blabla'
      price_per_hour: 1
    XS:
      path: '/sql/1.0/warehouses/blabla'
      price_per_hour: 2
    S:
      path: '/sql/1.0/warehouses/blabla'
      price_per_hour: 3
    M:
      path: '/sql/1.0/warehouses/blabla'
      price_per_hour: 4
    L:
      path: '/sql/1.0/warehouses/blabla'
      price_per_hour: 5
    XL:
      path: '/sql/1.0/warehouses/blabla'
      price_per_hour: 6
    2XL:
      path: '/sql/1.0/warehouses/blabla'
      price_per_hour: 7
    3XL:
      path: '/sql/1.0/warehouses/blabla'
      price_per_hour: 8
    4XL:
      path: '/sql/1.0/warehouses/blabla'
      price_per_hour: 9
